site_name: 'Awesome mPython'
site_url: 'http://awesome-micropython.com'
site_description: 'A curated list of MicroPython libraries, frameworks, software and resources.'
site_author: 'Mike Causer'
repo_name: 'tangliufeng/awesome-micropython'
repo_url: 'https://github.com/tangliufeng/awesome-micropython'
edit_uri: ''


theme:
  name: 'material'
  language: 'en'
  # logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'teal'
google_analytics: ['UA-1390021-18', 'awesome-micropython.com']
nav:
  - 'Awesome MicroPython': 'index.md'
plugins:
  - search
  - minify
